config/routes.rb
Rails.application.routes.draw do
  scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
    get 'sessions/new'

    get 'sessions/create'

    get 'sessions/destroy'

    resources :users
    resources :posts do
      resources :comments
      resources :likes
    end


    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
    root 'posts#index', as: 'home'
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, length: { minimum: 3 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3 }
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# class ApplicationController
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  protected

  def authorize
    return if User.find_by(id: session[:user_id])

    redirect_to '/login', notice: 'You trying to access without permit?'
  end

  def set_locale
    I18n.locale = params[:locale] if params[:locale].present?
  end

  def default_url_options(options = {})
    options.merge(locale: I18n.locale)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# class CommentsController
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(user_id: session[:user_id], body: comment_params[:body])
    redirect_to post_path(@post)
  end

  def show
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.required(:comment).permit(:body)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

# class LikesController
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    if @post.likes.all? { |like| like.user_id != session[:user_id] }
      @like = @post.likes.create(user_id: session[:user_id])
    end
    redirect_to post_path(@post)
  end

  def show
    @post = Post.find(params[:post_id])
    @like = @post.likes.find(params[:id])
    @like.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# class PostsController
class PostsController < ApplicationController
  before_action :authorize
  skip_before_action :authorize, only: :index
  before_action :set_post, only: %i[show edit update destroy]
  before_action :permit, only: %i[edit update destroy]

  def index
    @posts = Post.all
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(user_id: session[:user_id], title: post_params[:title], body: post_params[:body])
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def edit; end

  def destroy
    @post.destroy

    redirect_to posts_path
  end

  private

  def permit
    return unless session[:user_id] != @user.id && session[:user_id] != 1

    redirect_to @post, notice: 'You trying to access without permit?'
  end

  def set_post
    @post = Post.find(params[:id])
    @user = User.find_by_id(@post.user_id)
    @user_session = User.find_by_id(session[:user_id]).name
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# class SessionsController
class SessionsController < ApplicationController
  def new
    session[:user_id] = nil
  end

  def create
    user = User.find_by(name: params[:name])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      redirect_to login_path, notice: 'Invalid Username or Password'
    end
  end

  def destroy
    session[:users_id] = nil
    redirect_to login_path, notice: 'Successfully logged out'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# class UsersController
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize, only: %i[show edit update destroy index]
  before_action :permit, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    if User.find_by_name(user_params[:name])
      redirect_to new_user_path
    else
      @user = User.new(user_params)
      if @user.save
        redirect_to @user
      else
        redirect_to new_user_path
      end
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      redirect_to edit_user_path, notice: 'Please check the information !'
    end
  end

  def destroy
    @user.destroy

    redirect_to login_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

  def permit
    return unless session[:user_id] != @user.id && session[:user_id] != 1

    redirect_to @user, notice: 'You trying to access without permit?'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# module ApplicationHelper
module ApplicationHelper
end

app/helpers/sequence_helper.rb
# frozen_string_literal: true

# module SequenceHelper
module SequenceHelper
end

app/helpers/session_helper.rb
# frozen_string_literal: true

# module SessionHelper
module SessionHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# module UsersHelper
module UsersHelper
end

app/views/comments/_comments.html.erb
<% @post.comments.each do |comment| %>
  <% user = User.find_by_id(comment.user_id) %>
  <div class="well">
    <div class="col-md-10"><p><strong><i class="glyphicon glyphicon-user"></i> <%= user.name %></strong>: <%= comment.body %></p></div>
    <% if comment.user_id == session[:user_id] || session[:user_id] == 1 %>
      <div class="col-md-2 text-right">
        <%= link_to [comment.post, comment], method: :delete, data: {confirm: 'Are you sure?'} do %>
          <i class="glyphicon glyphicon-remove"></i><%= t "posts.show.delete" %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'main', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
    <% if session[:user_id] != nil %>
        <a class="navbar-brand"><%= t ".welcome"%> <%= User.find_by_id(session[:user_id]).name %></a>
        <ul class="nav navbar-nav">
          <li>
            <%= link_to home_path do %>
              <i class="glyphicon glyphicon-home"></i> <%= t '.home'%>
            <% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav">
          <li>
            <%= link_to new_post_path do %>
              <i class="glyphicon glyphicon-pencil"></i> <%= t '.create_post'%>
            <% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to login_path do %>
              <i class="glyphicon glyphicon-log-out"></i> <%= t '.log_out'%>
            <% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to users_path do %>
              <i class="glyphicon glyphicon-user"></i> <%= t '.users'%>
            <% end %>
          </li>
        </ul>
    <% else %>
      <a class="navbar-brand"><%= t ".hello" %></a>
        <ul class="nav navbar-nav">
          <li>
            <%= link_to home_path do %>
              <i class="glyphicon glyphicon-home"></i> <%= t '.home'%>
            <% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to login_path do %>
              <i class="glyphicon glyphicon-log-in"></i> <%= t 'sessions.new.log_in'%>
            <% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to new_user_path do %>
              <i class="glyphicon glyphicon-user"></i> <%= t 'users.new.new_user'%>
            <% end %>
          </li>
        </ul>
    <% end %>
    <ul class="nav navbar-nav navbar-right">
      <% if I18n.locale.to_s == 'ru' %>
        <li><%= link_to '<i class="glyphicon glyphicon-globe"></i> Русский'.html_safe, locale: "en" %></li>
      <% else %>
        <li><%= link_to '<i class="glyphicon glyphicon-globe"></i> English'.html_safe, locale: "ru" %></li>
      <% end %>
    </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/likes/_likes.html.erb
 <table>
      <tr>
        <td><%= @post.likes.count %></td>
        <% @post.likes.each do |like| %>
          <% user = User.find_by_id(like.user_id) %>
          <% if user != nil %>
            <td>
              <i class="glyphicon glyphicon-user"></i> <%= user.name %>
            </td>
          <% end %>
        <% end %>
      </tr>
 </table>




app/views/posts/edit.html.erb
<h1><%= t "posts.show.edit" %></h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label t ".title" %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label t ".body" %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit t ".save", class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1><%= t ".title" %></h1>
<% @posts.each do |post| %>
  <% user = User.find_by_id(post.user_id) %>
  <div class="well">
    <h2><%= post.title %> <span style="font-size: small"><%= t ".created" %> <i class="glyphicon glyphicon-user"></i><strong> <%= user.name %></strong></span></h2>
    <p><%= post.body %></p>
    <%= link_to post_path(post), :class => 'btn btn-default' do %>
    <%= t ".read_more" %>
    <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1><%= t ".new_post" %></h1>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label t "posts.edit.title" %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label t "posts.edit.body" %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit(t "posts.edit.save", class: "btn btn-primary") %>
  </p>
<% end %>


app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-8">
    <h2><i class="glyphicon glyphicon-user"></i> <%= @user.name %></h2>
    <h4><%= @post.title %></h4>
    <p><%= @post.body %></p>
  </div>
  <div class="col-md-4 text-right">
    <% if @post.user_id == session[:user_id] || session[:user_id] == 1 %>
      <a class="btn btn-default" href="<%= edit_post_path(@post) %>"><i class="glyphicon glyphicon-edit"></i> <%= t ".edit" %></a>
      <%= button_to post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} do %>
      <button class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> <%= t ".delete" %></button>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row">
  <% if @post.likes.all? { |like| like.user_id != session[:user_id] } %>
    <%= form_for [@post, @post.likes.build] do %>
      <%= button_tag type: 'submit', class: "btn" do %>
        <i class="glyphicon glyphicon-thumbs-up"> <%= t ".like" %></i>
      <% end %>
    <% end %>
  <% else %>
    <% @post.likes.each do |item| %>
      <% if item.user_id == session[:user_id] %>
        <%= link_to post_like_path(@post, item), method: :delete do %>
          <button class="btn btn-primary"><i class="glyphicon glyphicon-thumbs-up"> <%= t ".like" %></i></button>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<%= render 'likes/likes' %>

<div class="row text-center">
  <h5><%= t ".comments" %></h5>
</div>

<%= render 'comments/comments' %>

<h4><i class="glyphicon glyphicon-user"></i> <%= @user_session %></h4>

<%= form_for( [@post, @post.comments.build] ) do |f| %>
  <p>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit t ".create", class: "btn btn-primary" %>
  </p>
<% end %>

app/views/users/edit.html.erb
<p id="notice"><%= notice %></p>
<h1><%= t ".edit" %></h1>
<%= form_for :user, url: user_path(@user), method: :patch do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label t ".name" %><br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label t ".password" %><br>
    <%= f.password_field(:password, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label t ".confirm" %><br>
    <%= f.password_field(:password_confirmation, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit t ".edit", :class => 'btn btn-primary' %>
  </p>
<% end %>

app/views/users/index.html.erb
<h1><%= t "layouts.application.users" %></h1>
<% @users.each do |user| %>
  <div class="well">
    <h3><i class="glyphicon glyphicon-user"></i> <%= user.name %></h3>
    <%= link_to user, class: 'btn btn-default' do %>
      <i class="glyphicon glyphicon-resize-full"></i> <%= t "posts.index.read_more" %>
    <% end %>
    <% if session[:user_id] == user.id || session[:user_id] == 1 %>
      <%= link_to edit_user_path(user), class: 'btn btn-default' do %>
        <i class="glyphicon glyphicon-edit"></i> <%= t "posts.show.edit" %>
      <% end %>
      <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <button class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> <%= t "posts.show.delete" %></button>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1><%= t ".new_user" %></h1>
<%= form_for :user, url: users_path do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label t "users.edit.name" %><br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label t "users.edit.password" %><br>
    <%= f.password_field(:password, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label t "users.edit.confirm" %><br>
    <%= f.password_field(:password_confirmation, {:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit t "posts.edit.save", :class => 'btn btn-primary' %>
  </p>
<% end %>


app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2><i class="glyphicon glyphicon-user"></i> <%= @user.name %></h2>
<table class="table table-hover">
  <% @user.posts.each do |post| %>
    <tr>
      <td>
        <h4><%= post.title %></h4>
        <p><%= post.body %></p>
      </td>
      <td class="text-right">
        <a class="btn btn-default" href="<%= post_path(post) %>"><i class="glyphicon glyphicon-resize-full"></i> <%= t "posts.index.read_more" %></a>
      </td>
    </tr>
  <% end %>
</table>